name: test
on:
  push:
    branches: [ main,dev,qa ]


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo
        run: echo "commit on dev"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set env vars (dev)
        if: endsWith(github.ref, '/dev')
        run: echo "commit on dev"
      - name: Set env vars (prod)
        if: endsWith(github.ref, '/main')
        run: echo "commit on main"